[package]
name = "benches"
publish = false
edition.workspace = true

[dependencies]
metalogue = { path = "../crates/metalogue" }

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "adder_kernel_compilation"
path = "adder_kernel_compilation.rs"
harness = false
